# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'node'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['10.145.135.100:9090'] ## IP Address of the localhost
  - job_name: 'docker-metrics' 
    static_configs: 
      - targets: ['10.145.135.100:9323'] 
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['10.145.135.100:9100']