##################################################################################
# Step by Step 
#   1. Run below code from directory where this file is saved "GridDeployment.yml"
#         kubectl apply -f GridDeployment.yml
#   2. Let's get Selenium Grid Port by running below code
#         kubectl get all -l name=selenium-hub
#      Under PORT(S) column you will see exposed "4444:30443/TCP" we need this "30443" port.   
#   3. Now you can access to Grid with this url:
#         http://localhost:<yourPort>/grid/console
#
#   To check you running pods: kubectl get pods
##################################################################################

##################################################################################
# CREATE
#   kubectl apply -f GridDeployment.yml
# EXPOSE
#   kubectl expose deployment selenium-hub-deployment --type=NodePort --port=4444
# DELETE
#   kubectl delete -f GridDeployment.yml
# SCALE
#   kubectl scale deployment.apps/selenium-node-chrome-deployment --replicas=10
# AUTOSCALE
#   kubectl autoscale deployment selenium-node-chrome-deployment --cpu-percent=50 --min=1 --max=10
##################################################################################

#   kubectl get pods
#   kubectl get services
#   kubectl get deployments
#   kubectl get all
#   kubectl get all -l name=selenium-hub
#   kubectl logs deployment/selenium-node-chrome-deployment
#   kubectl logs deployment/selenium-node-chrome-deployment --follow
#   kubectl logs deployment/selenium-node-chrome-deployment --follow --tail 1
#   kubectl get pods -w
#
#   Grid URL: http://<ip>:<port>/grid/console

##################################################################################
# Selenium Hub Deployment
##################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:latest # selenium/hub:4.0.0
          ports:
            - containerPort: 4444
              protocol: TCP
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
---

##################################################################################
# Selenium Hub Service
##################################################################################
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: node
      protocol: TCP
      port: 5555
      targetPort: 5555
---

######################################
# Chrome Nodes
######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome-deployment
  labels:
    app: selenium-node-chrome
    name: selenium-node-chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:latest # selenium/node-chrome-debug:3.141
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: HUB_HOST
              value: "selenium-hub"
            - name: HUB_PORT
              value: "4444"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
---

######################################
# Firefox Node
######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-firefox-deployment
  labels:
    app: selenium-node-firefox
    name: selenium-node-firefox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-firefox
  template:
    metadata:
      labels:
        app: selenium-node-firefox
    spec:
      # nodeSelector: 
      #   newnode: worker2
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-firefox
        image: selenium/node-firefox:latest  # selenium/node-firefox-debug:3.141
        ports:
          - containerPort: 5900
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_HOST
            value: "selenium-hub"
          - name: HUB_PORT
            value: "4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
---

######################################
# Exposing Selenium Hub Port
######################################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-hub
    name: selenium-hub
  name: selenium-hub-deployment
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: selenium-hub
  type: NodePort
status:
  loadBalancer: {}
---