name: Edge with Java

on:
  workflow_dispatch:


env:
  REGISTRY: useast.jfrog.lexisnexisrisk.com
  IMAGE_NAME: edge-java

jobs:
  Package_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build the Docker Image
        run: docker build . --file dockerfiles/Edge/Java_Dockerfile --tag ${{ env.IMAGE_NAME }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Login to JFrog Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.Jfrog_username }}
          password: ${{ secrets.Jfrog_token }}

      - name: Tag and Push
        run: |
          docker tag ${{ env.IMAGE_NAME }} "${{ env.REGISTRY }}/sdet-base-images/${{ env.IMAGE_NAME }}:latest"
          docker push "${{ env.REGISTRY }}/sdet-base-images/${{ env.IMAGE_NAME }}:latest"